name: example
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.2"
  flutter_hello_package:
    path: "../"
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/test_asset_variants/test_png_variant_1.png
  - assets/images/test_only_main_asset_1.png
  - packages/example/assets/images/test_asset_variants/test_png_variant_2.png
  - packages/example/assets/images/test_only_main_asset_2.png
  - assets/texts/test.json
  - packages/example/assets/texts/test.yaml
  - assets/htmls/test.html
  - assets/htmls/test_html_asset_variant.png
  - assets/htmls/test_html_main_asset.png
  - packages/flutter_hello_package/assets/images/test_only_main_asset_2.png
  - packages/flutter_hello_package/assets/texts/test.yaml
  fonts:
  - family: Amiri
    fonts:
    - asset: packages/example/assets/fonts/Amiri/Amiri-Bold.ttf
    - asset: packages/example/assets/fonts/Amiri/Amiri-BoldItalic.ttf
    - asset: packages/example/assets/fonts/Amiri/Amiri-Italic.ttf
    - asset: packages/example/assets/fonts/Amiri/Amiri-Regular.ttf
  - family: Baloo_Thambi_2
    fonts:
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Bold.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-ExtraBold.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Medium.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Regular.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-SemiBold.ttf
  - family: Dan_Zhai_Hang_Shu_Cai
    fonts:
    - asset: packages/example/assets/fonts/Dan_Zhai_Hang_Shu_Cai/Dan_Zhai_Hang_Shu_Cai.ttc
  - family: Liu_Jian_Mao_Cao
    fonts:
    - asset: assets/fonts/Liu_Jian_Mao_Cao/LiuJianMaoCao-Regular.ttf
  - family: Lobster
    fonts:
    - asset: assets/fonts/Lobster/Lobster-Regular.ttf
  - family: Pacifico
    fonts:
    - asset: packages/example/assets/fonts/Pacifico/Pacifico-Regular.ttf
  - family: Sky_IconFont
    fonts:
    - asset: assets/fonts/Sky_IconFont/iconfont.ttf
  - family: YorkFish_IconFont
    fonts:
    - asset: packages/example/assets/fonts/YorkFish_IconFont/iconfont.ttf
flr:
  core_version: 3.2.0
  dartfmt_line_length: 100
  assets:
  - assets/images
  - assets/texts
  - lib/assets/images
  - lib/assets/texts
  fonts:
  - assets/fonts
  - lib/assets/fonts
